const pokes = [
  null,
  "bulbasaur",
  "venusaur",
  "charmander",
  "charmelion",
  "charizard",
  "squirtle",
  "pikachu",
  "wartortle",
  " blastoise",
  "caterpie",
  " metapod",
  "butterfree",
  "weedle",
  "kakuna",
  " beedrill",
  "pidgey",
  "pidgeotto",
  "rattata",
  "raticate",
];
const prices = [
  null,
  10,
  29,
  21,
  34,
  56,
  78,
  65,
  34,
  78,
  12,
  45,
  6,
  79,
  32,
  54,
  87,
  43,
  56,
  23,
];

const images = [
  null,
  "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1f619ed0-b566-4538-8392-bf02ca7a76cd/dck5gvr-d1a822f4-cb27-46b3-a0ad-5538b486b6f5.png/v1/fill/w_758,h_630/001_bulbasaur_png_0__6__by_andersonaas107_dck5gvr-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NjMwIiwicGF0aCI6IlwvZlwvMWY2MTllZDAtYjU2Ni00NTM4LTgzOTItYmYwMmNhN2E3NmNkXC9kY2s1Z3ZyLWQxYTgyMmY0LWNiMjctNDZiMy1hMGFkLTU1MzhiNDg2YjZmNS5wbmciLCJ3aWR0aCI6Ijw9NzU4In1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.4XApEhXwxzFwLhIcWpAfe1tb1141YYxw0vcT27tA5q4",
  "https://www.pngplay.com/wp-content/uploads/12/Venusaur-Pokemon-PNG-Photo-Clip-Art-Image.png",
  "https://www.pngmart.com/files/13/Pokemon-Charmander-PNG-Pic.png",
  "https://www.pngplay.com/wp-content/uploads/10/Charmeleon-Pokemon-PNG-Clipart-Background.png",
  "https://www.pngmart.com/files/12/Charizard-PNG-Free-Download.png",
  "https://www.pngplay.com/wp-content/uploads/12/Squirtle-Pokemon-Download-Free-PNG-Clip-Art.png",
  "https://www.pngplay.com/wp-content/uploads/11/Pikachu-Pokemon-Transparent-File.png",
  "https://www.pngmart.com/files/22/Wartortle-Pokemon-Transparent-Isolated-PNG.png",
  "https://www.nicepng.com/png/detail/150-1500390_blastoise-transparent-png-pokemon-blastoise-png.png",
  "https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png",
  "https://www.pngplay.com/wp-content/uploads/11/Metapod-Pokemon-PNG-HD-Quality.png",
  "https://www.pngmart.com/files/22/Butterfree-Pokemon-PNG-Image.png",
  "https://www.pngplay.com/wp-content/uploads/12/Weedle-Pokemon-PNG-HD-Images.png",
  "https://www.nicepng.com/png/detail/125-1251698_kakuna-pokemon-kakuna.png",
  "https://www.pngplay.com/wp-content/uploads/10/Beedrill-Pokemon-PNG-Photo-Image.png",
  "https://www.nicepng.com/png/detail/44-449019_pidgey-pidgey-pokemon.png",
  "https://images.wikidexcdn.net/mwuploads/wikidex/thumb/a/a9/latest/20141214190416/Pidgeot.png/1200px-Pidgeot.png",
  "https://images.wikidexcdn.net/mwuploads/wikidex/c/c4/latest/20200307022853/Rattata.png",
  "https://www.pngmart.com/files/22/Raticate-Pokemon-PNG.png",
];

const desc = [
  null,
  "Bulbasaur (フシギダネ Fushigidane) is a Grass/Poison-type Seed Pokémon and is the initial Pokémon in the National Pokédex, numbered #001. Bulbasaur evolves into Ivysaur at level 16 then Venusaur at level 32. It is the Grass-type Starter Pokémon in the Generation I games as well as Pokémon FireRed and LeafGreen",
  "Venusaur is a large, quadrupedal Pokémon with a turquoise body. It has small red eyes and several large ferns on its back and head. The plant bulb that was on the back of its previous evolutions, Bulbasaur and Ivysaur, has now bloomed into a large flower with large pink petals and a yellow center.",
  "Charmander is a small, bipedal, dinosaur like Pokémon. Most of its body is colored orange, while its underbelly is a light yellow color. Charmander, along with all of its evolved forms, has a flame that is constantly burning on the end of its tail.",
  "Charmeleon is a small, bipedal, dinosaur-like Pokémon with an appearance similar to that of its pre-evolved form, Charmander. Charmeleon differs from Charmander in that it has a much darker red skin color, a larger body structure, claws, and a horn-like protrusion on the back of its head, similar to that of an ornithopod's. Its claws are razor sharp and its tail is very strong.",
  "Charizard Described by the media as a lean, ferocious, fire-breathing dragon ... sleek, powerful, and utterly destructive, Charizard has been noted as one of the franchises most popular characters.",
  "Squirtles English name is a portmanteau of the words squirt and turtle Squirtle, known as the Tiny Turtle Pokémon, are turtle Pokémon with large eyes and chubby cheeks, capable of moving either on two feet or on all fours.",
  "Pikachu was designed around the concept of electricity. They are creatures that have short, yellow fur with brown markings covering their backs and parts of their lightning bolt-shaped tails. They have black-tipped, pointed ears and red circular pouches on their cheeks, which can spark with electricity.",
  "Wartortle is a bipedal, indigo reptilian Pokémon similar to a turtle. It has brown eyes, a dark blue streak on each cheek, and two sharp teeth protruding from its upper jaw. It has three clawed fingers and pointed toes. On each side of its head are feather-like ears covered in pale blue fur. A brown shell with a pale yellow underside encases its body",
  "Blastoise is a large, bipedal turtle Pokémon. Its body is blue and is mostly hidden by its tough, brown shell. This shell has a cream-colored underside and a white ridge encircling its arms and separating the upper and lower halves. Two powerful water cannons reside at the top of its shell over its shoulders. These cannons can be extended or withdrawn",
  "Caterpie is an insect Pokémon that resembles a green caterpillar with a yellow underside and teardrop-shaped tail. There are yellow ring-shaped markings down the sides of its segmented body, which resemble its eyes and are meant to scare off predators.",
  "Metapod is an insect Pokémon that resembles a green chrysalis. Its body is crescent-shaped with several segments making up the lower point. The front of Metapod's shell resembles a face with heavy-lidded eyes and a sharply pointed nose. The back of its shell consists of several geometrically shaped portions and projections",
  "Butterfree is a lepidopteran insect Pokémon which resembles a vaguely anthropomorphic butterfly with a purple body. Unlike true insects, it only has two body segments and four light blue legs. The upper pair of its legs resemble small, three-fingered hands, while the lower pair resembles long, digit-less feet. Butterfree has two black antennae, a light blue snout with two fangs underneath, and large, red compound eyes. Its two pairs of wings are white with black venation. Two oval scales on a female Butterfree's lower wings are black, but they are white on a male.",
  "Weedle is a larval insect Pokémon with a segmented body ranging in color from yellow to reddish-brown. Each segment of its body is a sphere. It has a bulbous red nose, two small, black eyes on its face and two spherical feet on each body segment. The combination of red and yellow in its color scheme creates a bright warning to predators that it is poisonous. ",
  "Kakuna is a yellow, insect cocoon-like Pokémon. Kakuna has a dome-shaped head and black, triangular eyes with glowing white pupils. It has two scythe-like arms in the middle of its body. When it comes close to evolving, its body gives off heat that makes it warm to the touch. Kakuna remains virtually immobile and waits for evolution, often hanging from tree branches by long strands of silk.",
  "Beedrill is an insect Pokémon which mostly resembles a bipedal, yellow wasp; however, it only has four legs instead of six and lacks pigment pits. Beedrill's head is round with a slightly pointed mouth; large, red eyes; and black antennae with a sharp bend in the middle. Its forelegs are tipped with long, conical stingers. It stands on its other two legs, which are long, segmented, and insectoid in shape. Beedrill has two pairs of rounded, veined wings and another stinger on its yellow-and-black striped abdomen. The abdominal stinger contains Beedrill's most potent poison",
  "Pidgey is a small, plump-bodied avian Pokémon. It is primarily brown with a cream-colored face, underside, and flight feathers. On top of its head is a short crest of three tufts. The center crest feathers are brown and the outer two tufts are cream-colored. Just under its crest are its narrow eyes which have white sclera and pupil along with its black irises.",
  "Pidgeotto is a raptor-like avian Pokémon. It is covered with brown feathers, has a cream-colored face, underside, and flight feathers. It has a crest of pinkish-red feathers on its head and black, angular markings behind its black eyes. The plumage of its tail has alternating red and yellow feathers with ragged tips. Pidgeotto's beak and legs are pink. Two of its toes point forward, while one points backward. Additionally, it has powerful, sharp talons that it uses to grasp prey. Pidgeotto is a powerful flier capable of carrying prey several miles to its nest. It has amazing vision, which helps it locate preferred prey Pokémon such as Exeggcute and Magikarp.",
  "Rattata is a small, quadrupedal rodent Pokémon. It has purple fur with a cream-colored face, paws, and underbelly. It has narrow eyes containing white sclera and pupil with red irises, rounded ears with cream-colored insides, and a single whisker on each cheek. Its long tail is tightly curled at the end. Its most notable feature is its large teeth. Like most rodents, its teeth grow continuously throughout its life and must be worn down by gnawing. A female Rattata will have shorter whiskers and lighter fur.",
  "Raticate is a large, rodent-like Pokémon. Although it is often depicted on its hind legs, it is a quadruped. It is primarily tawny-colored with a cream underside. It has narrow black eyes, ears with ragged edges and dark insides, and large incisors that grow constantly. There are three whiskers on each side of its face, which it uses to maintain balance. It has short arms with three-fingered hands and webbed feet with three toes. The webbing on its feet allows it to swim. Its tail is long and scaly. A female will have shorter whiskers and lighter fur."
]
const arrayObj = pokes.slice(1).map((name, index) => ({
  name: name,
  price: prices[index + 1],
  url: images[index + 1],
  description : desc[index+1]
}));

console.log(arrayObj);

export { arrayObj };
